"""Add userrole column to users

Revision ID: 0d425a69c6c2
Revises: c4a2006bad1b
Create Date: 2025-08-14 19:32:43.247889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d425a69c6c2'
down_revision: Union[str, Sequence[str], None] = 'c4a2006bad1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
    'users',
    sa.Column(
        'userrole',
        sa.Enum('candidate', 'recruiter', 'admin', name='userrole'),
        nullable=False,
        server_default='candidate'  # default role
    )
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userrole')
    # ### end Alembic commands ###
