"""Add userrole column to users

Revision ID: 4580569b9a6c
Revises: 0d425a69c6c2
Create Date: 2025-08-14 19:37:10.143524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4580569b9a6c'
down_revision: Union[str, Sequence[str], None] = '0d425a69c6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userrole', sa.Enum('candidate', 'recruiter', 'admin', name='userrole'), nullable=False,server_default='candidate'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userrole')
    # ### end Alembic commands ###
